#!/usr/bin/env python
import argparse # optparse is deprecated
from itertools import islice # slicing for iterators
 
def word_matches(h, ref):
    return sum(1 for w in h if w in ref)
def new_l(p, r):
    alpha =0.6
    num = p*r
    dino = (1-alpha)*r + alpha*p
    if dino==0:
        return 0
    return num/dino
 
def main():
    parser = argparse.ArgumentParser(description='Evaluate translation hypotheses.')
    parser.add_argument('-i', '--input', default='data/hyp1-hyp2-ref',
            help='input file (default data/hyp1-hyp2-ref)')
    parser.add_argument('-n', '--num_sentences', default=None, type=int,
            help='Number of hypothesis pairs to evaluate')
    # note that if x == [1, 2, 3], then x[:None] == x[:] == x (copy); no need for sys.maxint
    opts = parser.parse_args()
 
    # we create a generator and avoid loading all sentences into a list
    def sentences():
        #print("enter")
        with open(opts.input) as f:
            for pair in f:
                yield [sentence.strip().split() for sentence in pair.split(' ||| ')]
 
    # note: the -n option does not work in the original code
    # for h1, h2, ref in islice(sentences(), opts.num_sentences):
    #     rset = set(ref)
    #     h1_match = word_matches(h1, rset)
    #     h2_match = word_matches(h2, rset)
    #     print(1 if h1_match > h2_match else # \begin{cases}
    #             (0 if h1_match == h2_match
    #                 else -1)) # \end{cases}
    #print("in")
    for h1, h2, ref in islice(sentences(), opts.num_sentences):
        rset = set(ref)
        h1_match = word_matches(h1, rset)
        #print("---"*10,h1_match,len(h1))
        p_1 = float(h1_match)/len(h1)
        r_1 =  float(h1_match)/len(rset)
        #print(p_1,r_1)
        h1_match  = new_l(p_1, r_1)
        h2_match = word_matches(h2, rset)
        p_2 = float(h2_match)/len(h2)
        r_2 =  float(h2_match)/len(rset)
        h2_match  = new_l(p_2, r_2)

        print(1 if h1_match > h2_match else # \begin{cases}
                (0 if h1_match == h2_match
                    else -1)) # \end{cases}


# convention to allow import of this file as a module
if __name__ == '__main__':
    main()
